name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Create secrets.txt
        run: echo EMAIL_SECRET=jyotiprakash.nayak95@gmail.com > secrets.txt
        shell: powershell

      - name: Downloading & Setting Up
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
        shell: powershell

      - name: Execute downloaded batch file
        run: |
          Start-Process powershell -ArgumentList '-File', 'down.bat' -NoNewWindow -Wait
        shell: powershell

      - name: Create time.py
        run: |
          echo "import datetime" > time.py
          echo "" >> time.py
          echo "def main():" >> time.py
          echo "    current_time = datetime.datetime.now()" >> time.py
          echo "    print('Current date and time:', current_time)" >> time.py
          echo "" >> time.py
          echo "if __name__ == '__main__':" >> time.py
          echo "    main()" >> time.py
        shell: powershell

      - name: Time Counter
        run: python time.py
